// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartQ.Infrastructure.Persistence;

#nullable disable

namespace SmartQ.Infrastructure.Migrations
{
    [DbContext(typeof(SmartQDbContext))]
    [Migration("20260529081840_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartQ.Domain.Entities.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CounterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounterNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounterName = "Counter 01",
                            CounterNo = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            CounterName = "Counter 02",
                            CounterNo = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            CounterName = "Counter 03",
                            CounterNo = "03",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            CounterName = "Counter 04",
                            CounterNo = "04",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            CounterName = "Counter 05",
                            CounterNo = "05",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.CounterServiceAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CounterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CounterId", "IsActive");

                    b.HasIndex("ServiceId", "IsActive");

                    b.ToTable("CounterServiceAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounterId = 1,
                            IsActive = true,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 2,
                            CounterId = 2,
                            IsActive = true,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            CounterId = 3,
                            IsActive = true,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 4,
                            CounterId = 4,
                            IsActive = true,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            CounterId = 5,
                            IsActive = true,
                            ServiceId = 3
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DailyTokenSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SequenceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubServiceId");

                    b.HasIndex("SequenceDate", "SubServiceId", "TokenPrefix")
                        .IsUnique();

                    b.ToTable("DailyTokenSequences");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DisplayMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("DisplayMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            MessageKey = "TICKER_1",
                            MessageText = "PLEASE PROCEED TO YOUR COUNTER WHEN YOUR TOKEN IS CALLED"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            MessageKey = "TICKER_2",
                            MessageText = "DOWNLOAD THE SMARTQ APP FOR INSTANT NOTIFICATIONS"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            MessageKey = "TICKER_3",
                            MessageText = "THANK YOU FOR PATIENTLY WAITING AT SMARTQ BANK"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            MessageKey = "MOBILE_BANKING",
                            MessageText = "Scan QR on your receipt to track your turn live."
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDefault = true,
                            Name = "English",
                            NativeName = "English",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDefault = false,
                            Name = "Sinhala",
                            NativeName = "සිංහල",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Code = "TA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDefault = false,
                            Name = "Tamil",
                            NativeName = "தமிழ்",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CASH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Deposits, withdrawals, and currency exchange.",
                            DisplayOrder = 1,
                            Icon = "payments",
                            IsActive = true,
                            Name = "Cash Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Code = "ACC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Open new accounts, update profiles, and statement requests.",
                            DisplayOrder = 2,
                            Icon = "account_balance",
                            IsActive = true,
                            Name = "Account Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Code = "LOAN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Mortgages, personal loans, and credit consultations.",
                            DisplayOrder = 3,
                            Icon = "description",
                            IsActive = true,
                            Name = "Loan Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Code = "CARD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "New debit/credit cards, PIN resets, and card blockage.",
                            DisplayOrder = 4,
                            Icon = "credit_card",
                            IsActive = true,
                            Name = "Card Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Code = "HELP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "General inquiries, complaints, and digital banking assistance.",
                            DisplayOrder = 5,
                            Icon = "support_agent",
                            IsActive = true,
                            Name = "Customer Support",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.ServiceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "තැන්පතු, නිකුත් කිරීම් සහ මුදල් හුවමාරු.",
                            LanguageId = 2,
                            Name = "මුදල් සේවා",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "வைப்புகள், திரும்பப் பெறுதல்கள் மற்றும் நாணய பரிமாற்றம்.",
                            LanguageId = 3,
                            Name = "பண சேவைகள்",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "නව ගිණුම් විවෘත කිරීම සහ ප්‍රකාශන ඉල්ලීම්.",
                            LanguageId = 2,
                            Name = "ගිණුම් සේවා",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "புதிய கணக்குகள் மற்றும் அறிக்கை கோரிக்கைகள்.",
                            LanguageId = 3,
                            Name = "கணக்கு சேவைகள்",
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.StaffUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CounterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.ToTable("StaffUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounterId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "sarah@smartq.bank",
                            FullName = "Officer Sarah",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAE",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Username = "sarah"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@smartq.bank",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAE",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedServiceMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TokenPrefix");

                    b.HasIndex("ServiceId", "Code")
                        .IsUnique();

                    b.HasIndex("ServiceId", "IsActive", "DisplayOrder");

                    b.ToTable("SubServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CASH_DEP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Deposit cash into personal or business accounts.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 8,
                            Icon = "savings",
                            IsActive = true,
                            Name = "Cash Deposit",
                            ServiceId = 1,
                            TokenPrefix = "CD",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Code = "CASH_WD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "In-person cash withdrawals for amounts above ATM limits.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 12,
                            Icon = "atm",
                            IsActive = true,
                            Name = "Cash Withdrawal",
                            ServiceId = 1,
                            TokenPrefix = "CW",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Code = "CASH_TR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Transfer cash between accounts or to external beneficiaries.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 5,
                            Icon = "swap_horiz",
                            IsActive = true,
                            Name = "Cash Transfer",
                            ServiceId = 1,
                            TokenPrefix = "CT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Code = "FX",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Buy or sell foreign currency at competitive bank rates.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 15,
                            Icon = "currency_exchange",
                            IsActive = true,
                            Name = "Foreign Currency",
                            ServiceId = 1,
                            TokenPrefix = "FC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Code = "NA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Open a new savings or current account.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 20,
                            Icon = "person_add",
                            IsActive = true,
                            Name = "New Account Opening",
                            ServiceId = 2,
                            TokenPrefix = "NA",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Code = "AU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Update account profile and contact details.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 10,
                            Icon = "edit",
                            IsActive = true,
                            Name = "Account Update",
                            ServiceId = 2,
                            TokenPrefix = "AU",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Code = "SR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Request printed or digital account statements.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 8,
                            Icon = "receipt_long",
                            IsActive = true,
                            Name = "Statement Request",
                            ServiceId = 2,
                            TokenPrefix = "SR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Code = "PU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Update passbook with recent transactions.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 5,
                            Icon = "menu_book",
                            IsActive = true,
                            Name = "Passbook Update",
                            ServiceId = 2,
                            TokenPrefix = "PU",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Code = "LN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "General loan information and eligibility check.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 15,
                            Icon = "help",
                            IsActive = true,
                            Name = "Loan Inquiry",
                            ServiceId = 3,
                            TokenPrefix = "LN",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Code = "LA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Submit a new loan application.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 30,
                            Icon = "assignment",
                            IsActive = true,
                            Name = "Loan Application",
                            ServiceId = 3,
                            TokenPrefix = "LA",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Code = "LP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Make loan installment payments.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 10,
                            Icon = "paid",
                            IsActive = true,
                            Name = "Loan Payment",
                            ServiceId = 3,
                            TokenPrefix = "LP",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Code = "LD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Submit loan-related documents.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 12,
                            Icon = "upload_file",
                            IsActive = true,
                            Name = "Document Submission",
                            ServiceId = 3,
                            TokenPrefix = "LD",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Code = "NC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Request a new debit or credit card.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 15,
                            Icon = "add_card",
                            IsActive = true,
                            Name = "New Card Request",
                            ServiceId = 4,
                            TokenPrefix = "NC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Code = "CR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Replace damaged or expired cards.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 12,
                            Icon = "credit_card",
                            IsActive = true,
                            Name = "Card Replacement",
                            ServiceId = 4,
                            TokenPrefix = "CR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Code = "PR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Reset card PIN at the branch.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 8,
                            Icon = "pin",
                            IsActive = true,
                            Name = "PIN Reset",
                            ServiceId = 4,
                            TokenPrefix = "PR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Code = "LC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Report lost or stolen cards.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 10,
                            Icon = "report",
                            IsActive = true,
                            Name = "Lost Card Complaint",
                            ServiceId = 4,
                            TokenPrefix = "LC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Code = "GEN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "General banking inquiries.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 10,
                            Icon = "help_outline",
                            IsActive = true,
                            Name = "General Inquiry",
                            ServiceId = 5,
                            TokenPrefix = "GI",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Code = "COMP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Register a customer complaint.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 15,
                            Icon = "feedback",
                            IsActive = true,
                            Name = "Complaint",
                            ServiceId = 5,
                            TokenPrefix = "CP",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Code = "DIG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Digital banking assistance.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 12,
                            Icon = "smartphone",
                            IsActive = true,
                            Name = "Digital Banking",
                            ServiceId = 5,
                            TokenPrefix = "DB",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubServiceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SubServiceId");

                    b.ToTable("SubServiceTranslations");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = "string",
                            Description = "Daily token sequence reset mode",
                            IsActive = true,
                            SettingKey = "TOKEN_RESET_MODE",
                            SettingValue = "DAILY"
                        },
                        new
                        {
                            Id = 2,
                            DataType = "bool",
                            Description = "Enable voice announcements on display",
                            IsActive = true,
                            SettingKey = "ENABLE_VOICE_ANNOUNCEMENT",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 3,
                            DataType = "bool",
                            Description = "Enable token printing on kiosk",
                            IsActive = true,
                            SettingKey = "ENABLE_PRINT_TOKEN",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 4,
                            DataType = "int",
                            Description = "Number of recently called tokens on display",
                            IsActive = true,
                            SettingKey = "DISPLAY_RECENT_CALL_COUNT",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = 5,
                            DataType = "int",
                            Description = "Number of waiting tokens on display",
                            IsActive = true,
                            SettingKey = "DISPLAY_WAITING_QUEUE_COUNT",
                            SettingValue = "5"
                        },
                        new
                        {
                            Id = 6,
                            DataType = "int",
                            Description = "Default estimated wait minutes",
                            IsActive = true,
                            SettingKey = "DEFAULT_ESTIMATED_WAIT_MINUTES",
                            SettingValue = "8"
                        },
                        new
                        {
                            Id = 7,
                            DataType = "int",
                            Description = "Kiosk auto return seconds after finish",
                            IsActive = true,
                            SettingKey = "KIOSK_AUTO_RETURN_SECONDS",
                            SettingValue = "5"
                        },
                        new
                        {
                            Id = 8,
                            DataType = "bool",
                            Description = "Priority tokens called before standard",
                            IsActive = true,
                            SettingKey = "ENABLE_PRIORITY_QUEUE",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 9,
                            DataType = "string",
                            Description = "Branch identifier",
                            IsActive = true,
                            SettingKey = "BRANCH_ID",
                            SettingValue = "BR-9904"
                        },
                        new
                        {
                            Id = 10,
                            DataType = "string",
                            Description = "Branch display name",
                            IsActive = true,
                            SettingKey = "BRANCH_NAME",
                            SettingValue = "SmartQ Bank Central Branch"
                        },
                        new
                        {
                            Id = 11,
                            DataType = "string",
                            Description = "Kiosk software version",
                            IsActive = true,
                            SettingKey = "KIOSK_VERSION",
                            SettingValue = "v2.4"
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CounterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedWaitMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TokenNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tokens_CreatedAt");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TokenNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Tokens_TokenNo");

                    b.HasIndex("CounterId", "Status")
                        .HasDatabaseName("IX_Tokens_CounterId_Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Tokens_Status_CreatedAt");

                    b.HasIndex("ServiceId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_Tokens_ServiceId_Status_CreatedAt");

                    b.HasIndex("SubServiceId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_Tokens_SubServiceId_Status_CreatedAt");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.TokenStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CounterId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffUserId")
                        .HasColumnType("int");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenId", "ChangedAt");

                    b.ToTable("TokenStatusHistories");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.VoiceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("VoiceTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventType = "TOKEN_CALLED",
                            IsActive = true,
                            LanguageId = 1,
                            TemplateText = "Token number {tokenNo}, please proceed to {counterName}"
                        },
                        new
                        {
                            Id = 2,
                            EventType = "TOKEN_CALLED",
                            IsActive = true,
                            LanguageId = 2,
                            TemplateText = "ටෝකන් අංකය {tokenNo}, කරුණාකර {counterName} වෙත එන්න"
                        },
                        new
                        {
                            Id = 3,
                            EventType = "TOKEN_CALLED",
                            IsActive = true,
                            LanguageId = 3,
                            TemplateText = "டோக்கன் எண் {tokenNo}, {counterName} க்குச் செல்லவும்"
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.CounterServiceAssignment", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Counter", "Counter")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("CounterAssignments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DailyTokenSequence", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.SubService", "SubService")
                        .WithMany("DailySequences")
                        .HasForeignKey("SubServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DisplayMessage", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("DisplayMessages")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.ServiceTranslation", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("ServiceTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("Translations")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.StaffUser", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Counter", "Counter")
                        .WithMany("StaffUsers")
                        .HasForeignKey("CounterId");

                    b.Navigation("Counter");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubService", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("SubServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubServiceTranslation", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("SubServiceTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.SubService", "SubService")
                        .WithMany("Translations")
                        .HasForeignKey("SubServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Token", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Counter", "Counter")
                        .WithMany("Tokens")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("Tokens")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("Tokens")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.SubService", "SubService")
                        .WithMany("Tokens")
                        .HasForeignKey("SubServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Language");

                    b.Navigation("Service");

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.TokenStatusHistory", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Token", "Token")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.VoiceTemplate", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("VoiceTemplates")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Counter", b =>
                {
                    b.Navigation("ServiceAssignments");

                    b.Navigation("StaffUsers");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Language", b =>
                {
                    b.Navigation("DisplayMessages");

                    b.Navigation("ServiceTranslations");

                    b.Navigation("SubServiceTranslations");

                    b.Navigation("Tokens");

                    b.Navigation("VoiceTemplates");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Service", b =>
                {
                    b.Navigation("CounterAssignments");

                    b.Navigation("SubServices");

                    b.Navigation("Tokens");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubService", b =>
                {
                    b.Navigation("DailySequences");

                    b.Navigation("Tokens");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Token", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
