// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartQ.Infrastructure.Persistence;

#nullable disable

namespace SmartQ.Infrastructure.Migrations
{
    [DbContext(typeof(SmartQDbContext))]
    [Migration("20260605042836_FixDailyTokenUniqueness")]
    partial class FixDailyTokenUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartQ.Domain.Entities.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CounterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounterNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounterName = "Counter 01",
                            CounterNo = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            CounterName = "Counter 02",
                            CounterNo = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            CounterName = "Counter 03",
                            CounterNo = "03",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            CounterName = "Counter 04",
                            CounterNo = "04",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            CounterName = "Counter 05",
                            CounterNo = "05",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.CounterServiceAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CounterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CounterId", "IsActive");

                    b.HasIndex("ServiceId", "IsActive");

                    b.ToTable("CounterServiceAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounterId = 1,
                            IsActive = true,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 2,
                            CounterId = 2,
                            IsActive = true,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            CounterId = 3,
                            IsActive = true,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 4,
                            CounterId = 4,
                            IsActive = true,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            CounterId = 5,
                            IsActive = true,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 6,
                            CounterId = 1,
                            IsActive = true,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DailyTokenSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SequenceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubServiceId");

                    b.HasIndex("SequenceDate", "SubServiceId", "TokenPrefix")
                        .IsUnique();

                    b.ToTable("DailyTokenSequences");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DisplayMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("DisplayMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            MessageKey = "TICKER_1",
                            MessageText = "PLEASE PROCEED TO YOUR COUNTER WHEN YOUR TOKEN IS CALLED"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            MessageKey = "TICKER_2",
                            MessageText = "DOWNLOAD THE SMARTQ APP FOR INSTANT NOTIFICATIONS"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            MessageKey = "TICKER_3",
                            MessageText = "THANK YOU FOR PATIENTLY WAITING AT SMARTQ BANK"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            MessageKey = "MOBILE_BANKING",
                            MessageText = "Scan QR on your receipt to track your turn live."
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            MessageKey = "STAFF_EMPTY_QUEUE_TITLE",
                            MessageText = "No active token"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IsActive = true,
                            MessageKey = "STAFF_EMPTY_QUEUE_DESCRIPTION",
                            MessageText = "The counter is currently idle. Click Call Next to serve the next customer in the priority queue."
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IsActive = true,
                            MessageKey = "STAFF_CALL_NEXT_LOCKED_MESSAGE",
                            MessageText = "Complete or skip current token before calling next"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            IsActive = true,
                            MessageKey = "STAFF_TRANSFER_WARNING",
                            MessageText = "Transferred token will leave this counter's queue and be added to the destination's waiting list immediately."
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            IsActive = true,
                            MessageKey = "STAFF_COUNTER_SERVES_MESSAGE",
                            MessageText = "You are currently handling assigned services for this counter."
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            IsActive = true,
                            MessageKey = "STAFF_TV_BRANCH_MESSAGE",
                            MessageText = "Public display shows branch-wide waiting and called tokens."
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            IsActive = true,
                            MessageKey = "STAFF_MY_COUNTER_GREETING",
                            MessageText = "You are currently handling the priority queue for assigned services."
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            IsActive = true,
                            MessageKey = "STAFF_MY_COUNTER_IDLE",
                            MessageText = "No active token. Go to Queue Console to call the next customer."
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            IsActive = true,
                            MessageKey = "STAFF_CUSTOMER_LABEL_VIP",
                            MessageText = "Priority Member"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            IsActive = true,
                            MessageKey = "STAFF_CUSTOMER_LABEL_STANDARD",
                            MessageText = "Regular Member"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            IsActive = true,
                            MessageKey = "STAFF_QUEUE_PRESSURE_HIGH",
                            MessageText = "Queue pressure is high. Avoid taking breaks at this time."
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            IsActive = true,
                            MessageKey = "STAFF_QUEUE_PRESSURE_NORMAL",
                            MessageText = "Queue pressure is moderate."
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            IsActive = true,
                            MessageKey = "STAFF_QUEUE_PRESSURE_LOW",
                            MessageText = "Queue pressure is low."
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            IsActive = true,
                            MessageKey = "STAFF_COUNTER_STATUS_AVAILABLE_OK",
                            MessageText = "Counter is now available."
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            IsActive = true,
                            MessageKey = "STAFF_COUNTER_STATUS_BUSY_OK",
                            MessageText = "Counter marked as busy."
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            IsActive = true,
                            MessageKey = "STAFF_COUNTER_STATUS_BREAK_OK",
                            MessageText = "Break started. Counter is offline."
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 21,
                            IsActive = true,
                            MessageKey = "STAFF_COUNTER_STATUS_OFFLINE_OK",
                            MessageText = "Counter marked offline."
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 22,
                            IsActive = true,
                            MessageKey = "STAFF_COUNTER_STATUS_ACTIVE_BLOCK",
                            MessageText = "Complete current token before setting available."
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 23,
                            IsActive = true,
                            MessageKey = "STAFF_EFFICIENCY_TREND",
                            MessageText = "+2% since last hour"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 24,
                            IsActive = true,
                            MessageKey = "STAFF_SHIFT_ENDED",
                            MessageText = "Shift ended"
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDefault = true,
                            Name = "English",
                            NativeName = "English",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDefault = false,
                            Name = "Sinhala",
                            NativeName = "සිංහල",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Code = "TA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDefault = false,
                            Name = "Tamil",
                            NativeName = "தமிழ்",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CASH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Deposits, withdrawals, and currency exchange.",
                            DisplayOrder = 1,
                            Icon = "payments",
                            IsActive = true,
                            Name = "Cash Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Code = "ACC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Open new accounts, update profiles, and statement requests.",
                            DisplayOrder = 2,
                            Icon = "account_balance",
                            IsActive = true,
                            Name = "Account Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Code = "LOAN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Mortgages, personal loans, and credit consultations.",
                            DisplayOrder = 3,
                            Icon = "description",
                            IsActive = true,
                            Name = "Loan Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Code = "CARD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "New debit/credit cards, PIN resets, and card blockage.",
                            DisplayOrder = 4,
                            Icon = "credit_card",
                            IsActive = true,
                            Name = "Card Services",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Code = "HELP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "General inquiries, complaints, and digital banking assistance.",
                            DisplayOrder = 5,
                            Icon = "support_agent",
                            IsActive = true,
                            Name = "Customer Support",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.ServiceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "තැන්පතු, නිකුත් කිරීම් සහ මුදල් හුවමාරු.",
                            LanguageId = 2,
                            Name = "මුදල් සේවා",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "வைப்புகள், திரும்பப் பெறுதல்கள் மற்றும் நாணய பரிமாற்றம்.",
                            LanguageId = 3,
                            Name = "பண சேவைகள்",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "නව ගිණුම් විවෘත කිරීම, යාවත්කාලීන කිරීම් සහ ප්‍රකාශන ඉල්ලීම්.",
                            LanguageId = 2,
                            Name = "ගිණුම් සේවා",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "புதிய கணக்குகள், புதுப்பிப்புகள் மற்றும் அறிக்கை கோரிக்கைகள்.",
                            LanguageId = 3,
                            Name = "கணக்கு சேவைகள்",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "උපනිවේශ, පුද්ගලික ණය සහ ණය උපදේශන.",
                            LanguageId = 2,
                            Name = "ණය සේවා",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "அடமானம், தனிப்பட்ட கடன் மற்றும் கடன் ஆலோசனை.",
                            LanguageId = 3,
                            Name = "கடன் சேவைகள்",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "නව කාඩ්, PIN යළි පිහිටුවීම් සහ කාඩ් අවහිර කිරීම.",
                            LanguageId = 2,
                            Name = "කාඩ් සේවා",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "புதிய அட்டை, PIN மீட்டமைப்பு மற்றும் அட்டை தடுப்பு.",
                            LanguageId = 3,
                            Name = "அட்டை சேவைகள்",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "පොදු විමසීම්, පැමිණිලි සහ ඩිජිටල් බැංකු සහාය.",
                            LanguageId = 2,
                            Name = "පාරිභෝගික සහාය",
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "பொது விசாரணைகள், புகார்கள் மற்றும் டிஜிட்டல் வங்கி உதவி.",
                            LanguageId = 3,
                            Name = "வாடிக்கையாளர் ஆதரவு",
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.StaffUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CounterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("StaffUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounterId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "sarah@smartq.bank",
                            FullName = "Officer Sarah",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAE",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Username = "sarah"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@smartq.bank",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAE",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedServiceMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TokenPrefix");

                    b.HasIndex("ServiceId", "Code")
                        .IsUnique();

                    b.HasIndex("ServiceId", "IsActive", "DisplayOrder");

                    b.ToTable("SubServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CASH_DEP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Deposit cash into personal or business accounts.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 8,
                            Icon = "savings",
                            IsActive = true,
                            Name = "Cash Deposit",
                            ServiceId = 1,
                            TokenPrefix = "CD",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Code = "CASH_WD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "In-person cash withdrawals for amounts above ATM limits.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 12,
                            Icon = "atm",
                            IsActive = true,
                            Name = "Cash Withdrawal",
                            ServiceId = 1,
                            TokenPrefix = "CW",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Code = "CASH_TR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Transfer cash between accounts or to external beneficiaries.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 5,
                            Icon = "swap_horiz",
                            IsActive = true,
                            Name = "Cash Transfer",
                            ServiceId = 1,
                            TokenPrefix = "CT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Code = "FX",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Buy or sell foreign currency at competitive bank rates.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 15,
                            Icon = "currency_exchange",
                            IsActive = true,
                            Name = "Foreign Currency",
                            ServiceId = 1,
                            TokenPrefix = "FC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Code = "NA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Open a new savings or current account.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 20,
                            Icon = "person_add",
                            IsActive = true,
                            Name = "New Account Opening",
                            ServiceId = 2,
                            TokenPrefix = "NA",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Code = "AU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Update account profile and contact details.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 10,
                            Icon = "edit",
                            IsActive = true,
                            Name = "Account Update",
                            ServiceId = 2,
                            TokenPrefix = "AU",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Code = "SR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Request printed or digital account statements.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 8,
                            Icon = "receipt_long",
                            IsActive = true,
                            Name = "Statement Request",
                            ServiceId = 2,
                            TokenPrefix = "SR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Code = "PU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Update passbook with recent transactions.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 5,
                            Icon = "menu_book",
                            IsActive = true,
                            Name = "Passbook Update",
                            ServiceId = 2,
                            TokenPrefix = "PU",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Code = "LN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "General loan information and eligibility check.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 15,
                            Icon = "help",
                            IsActive = true,
                            Name = "Loan Inquiry",
                            ServiceId = 3,
                            TokenPrefix = "LN",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Code = "LA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Submit a new loan application.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 30,
                            Icon = "assignment",
                            IsActive = true,
                            Name = "Loan Application",
                            ServiceId = 3,
                            TokenPrefix = "LA",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Code = "LP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Make loan installment payments.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 10,
                            Icon = "paid",
                            IsActive = true,
                            Name = "Loan Payment",
                            ServiceId = 3,
                            TokenPrefix = "LP",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Code = "LD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Submit loan-related documents.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 12,
                            Icon = "upload_file",
                            IsActive = true,
                            Name = "Document Submission",
                            ServiceId = 3,
                            TokenPrefix = "LD",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Code = "NC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Request a new debit or credit card.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 15,
                            Icon = "add_card",
                            IsActive = true,
                            Name = "New Card Request",
                            ServiceId = 4,
                            TokenPrefix = "NC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Code = "CR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Replace damaged or expired cards.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 12,
                            Icon = "credit_card",
                            IsActive = true,
                            Name = "Card Replacement",
                            ServiceId = 4,
                            TokenPrefix = "CR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Code = "PR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Reset card PIN at the branch.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 8,
                            Icon = "pin",
                            IsActive = true,
                            Name = "PIN Reset",
                            ServiceId = 4,
                            TokenPrefix = "PR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Code = "LC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Report lost or stolen cards.",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 10,
                            Icon = "report",
                            IsActive = true,
                            Name = "Lost Card Complaint",
                            ServiceId = 4,
                            TokenPrefix = "LC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Code = "GEN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "General banking inquiries.",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 10,
                            Icon = "help_outline",
                            IsActive = true,
                            Name = "General Inquiry",
                            ServiceId = 5,
                            TokenPrefix = "GI",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Code = "COMP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Register a customer complaint.",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 15,
                            Icon = "feedback",
                            IsActive = true,
                            Name = "Complaint",
                            ServiceId = 5,
                            TokenPrefix = "CP",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Code = "DIG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Digital banking assistance.",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 12,
                            Icon = "smartphone",
                            IsActive = true,
                            Name = "Digital Banking",
                            ServiceId = 5,
                            TokenPrefix = "DB",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubServiceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SubServiceId");

                    b.ToTable("SubServiceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "පුද්ගලික හෝ ව්‍යාපාරික ගිණුම්වලට මුදල් තැන්පත් කරන්න.",
                            LanguageId = 2,
                            Name = "මුදල් තැන්පතු",
                            SubServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "தனிப்பட்ட அல்லது வணிகக் கணக்குகளில் பணம் வைக்கவும்.",
                            LanguageId = 3,
                            Name = "பண வைப்பு",
                            SubServiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "ATM සීමාවට වඩා වැඩි මුදල් නිකුත් කිරීම්.",
                            LanguageId = 2,
                            Name = "මුදල් නිකුත් කිරීම",
                            SubServiceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "ATM வரம்பை விட அதிகமான பண எடுப்புகள்.",
                            LanguageId = 3,
                            Name = "பண எடுப்பு",
                            SubServiceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "ගිණුම් අතර හෝ බාහිර ප්‍රතිලාභීන්ට මුදල් මාරු කිරීම.",
                            LanguageId = 2,
                            Name = "මුදල් මාරු කිරීම",
                            SubServiceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "கணக்குகளுக்கு இடையில் அல்லது வெளிப்புறர்களுக்கு பணம் அனுப்புதல்.",
                            LanguageId = 3,
                            Name = "பண பரிமாற்றம்",
                            SubServiceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "තරඟකාරී අනුපාතයන්හි විදේශ මුදල් මිලදී ගැනීම/විකිණීම.",
                            LanguageId = 2,
                            Name = "විදේශ මුදල්",
                            SubServiceId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "போட்டி விகிதங்களில் வெளிநாட்டு நாணயம் வாங்க/விற்.",
                            LanguageId = 3,
                            Name = "வெளிநாட்டு நாணயம்",
                            SubServiceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "නව ඉතිරිකිරීම් හෝ ධාවක ගිණුමක් විවෘත කරන්න.",
                            LanguageId = 2,
                            Name = "නව ගිණුම් විවෘත කිරීම",
                            SubServiceId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "புதிய சேமிப்பு அல்லது நடப்புக் கணக்கைத் திறக்கவும்.",
                            LanguageId = 3,
                            Name = "புதிய கணக்கு திறப்பு",
                            SubServiceId = 5
                        },
                        new
                        {
                            Id = 11,
                            Description = "ගිණුම් පැතිකඩ සහ සම්බන්ධතා තොරතුරු යාවත්කාලීන කරන්න.",
                            LanguageId = 2,
                            Name = "ගිණුම් යාවත්කාලීන කිරීම",
                            SubServiceId = 6
                        },
                        new
                        {
                            Id = 12,
                            Description = "கணக்கு விவரங்களைப் புதுப்பிக்கவும்.",
                            LanguageId = 3,
                            Name = "கணக்கு புதுப்பிப்பு",
                            SubServiceId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "මුද්‍රිත හෝ ඩිජිටල් ගිණුම් ප්‍රකාශන ඉල්ලන්න.",
                            LanguageId = 2,
                            Name = "ප්‍රකාශන ඉල්ලීම",
                            SubServiceId = 7
                        },
                        new
                        {
                            Id = 14,
                            Description = "அச்சு அல்லது டிஜிட்டல் அறிக்கையைக் கோருங்கள்.",
                            LanguageId = 3,
                            Name = "அறிக்கை கோரிக்கை",
                            SubServiceId = 7
                        },
                        new
                        {
                            Id = 15,
                            Description = "මෑත ගනුදෙනු සහිත පාස්පොත යාවත්කාලීන කරන්න.",
                            LanguageId = 2,
                            Name = "පාස්පොත් යාවත්කාලීනය",
                            SubServiceId = 8
                        },
                        new
                        {
                            Id = 16,
                            Description = "சமீபத்திய பரிவர்த்தனைகளுடன் பாஸ்புக் புதுப்பிக்கவும்.",
                            LanguageId = 3,
                            Name = "பாஸ்புக் புதுப்பிப்பு",
                            SubServiceId = 8
                        },
                        new
                        {
                            Id = 17,
                            Description = "සාමාන්‍ය ණය තොරතුරු සහ සුදුසුකම් පරීක්ෂාව.",
                            LanguageId = 2,
                            Name = "ණය විමසීම",
                            SubServiceId = 9
                        },
                        new
                        {
                            Id = 18,
                            Description = "பொது கடன் தகவல் மற்றும் தகுதி சரிபார்ப்பு.",
                            LanguageId = 3,
                            Name = "கடன் விசாரணை",
                            SubServiceId = 9
                        },
                        new
                        {
                            Id = 19,
                            Description = "නව ණය අයදුමක් ඉදිරිපත් කරන්න.",
                            LanguageId = 2,
                            Name = "ණය අයදුම",
                            SubServiceId = 10
                        },
                        new
                        {
                            Id = 20,
                            Description = "புதிய கடன் விண்ணப்பத்தைச் சமர்ப்பிக்கவும்.",
                            LanguageId = 3,
                            Name = "கடன் விண்ணப்பம்",
                            SubServiceId = 10
                        },
                        new
                        {
                            Id = 21,
                            Description = "ණය වාරික ගෙවීම් කරන්න.",
                            LanguageId = 2,
                            Name = "ණය ගෙවීම",
                            SubServiceId = 11
                        },
                        new
                        {
                            Id = 22,
                            Description = "கடன் தவணைகளைச் செலுத்துங்கள்.",
                            LanguageId = 3,
                            Name = "கடன் செலுத்துதல்",
                            SubServiceId = 11
                        },
                        new
                        {
                            Id = 23,
                            Description = "ණය සම්බන්ධ ලේඛන ඉදිරිපත් කරන්න.",
                            LanguageId = 2,
                            Name = "ලේඛන ඉදිරිපත් කිරීම",
                            SubServiceId = 12
                        },
                        new
                        {
                            Id = 24,
                            Description = "கடன் தொடர்பான ஆவணங்களைச் சமர்ப்பிக்கவும்.",
                            LanguageId = 3,
                            Name = "ஆவண சமர்ப்பிப்பு",
                            SubServiceId = 12
                        },
                        new
                        {
                            Id = 25,
                            Description = "නව ඩෙබිට්/ක්‍රෙඩිට් කාඩ් ඉල්ලන්න.",
                            LanguageId = 2,
                            Name = "නව කාඩ් ඉල්ලීම",
                            SubServiceId = 13
                        },
                        new
                        {
                            Id = 26,
                            Description = "புதிய டெபிட்/கிரெடிட் அட்டையைக் கோருங்கள்.",
                            LanguageId = 3,
                            Name = "புதிய அட்டை கோரிக்கை",
                            SubServiceId = 13
                        },
                        new
                        {
                            Id = 27,
                            Description = "හානි වූ හෝ කල් ඉකුත් වූ කාඩ් ප්‍රතිස්ථාපනය.",
                            LanguageId = 2,
                            Name = "කාඩ් ප්‍රතිස්ථාපනය",
                            SubServiceId = 14
                        },
                        new
                        {
                            Id = 28,
                            Description = "சேதமடைந்த அல்லது காலாவதியான அட்டைகளை மாற்றவும்.",
                            LanguageId = 3,
                            Name = "அட்டை மாற்றம்",
                            SubServiceId = 14
                        },
                        new
                        {
                            Id = 29,
                            Description = "ශාඛාවේදී කාඩ් PIN යළි පිහිටුවන්න.",
                            LanguageId = 2,
                            Name = "PIN යළි පිහිටුවීම",
                            SubServiceId = 15
                        },
                        new
                        {
                            Id = 30,
                            Description = "கிளையில் அட்டை PIN மீட்டமைக்கவும்.",
                            LanguageId = 3,
                            Name = "PIN மீட்டமைப்பு",
                            SubServiceId = 15
                        },
                        new
                        {
                            Id = 31,
                            Description = "නැතිවූ හෝ සොරකම් කළ කාඩ් වාර්තා කරන්න.",
                            LanguageId = 2,
                            Name = "නැතිවූ කාඩ් පැමිණිලි",
                            SubServiceId = 16
                        },
                        new
                        {
                            Id = 32,
                            Description = "இழந்த அல்லது திருடப்பட்ட அட்டையைப் புகாரளிக்கவும்.",
                            LanguageId = 3,
                            Name = "இழந்த அட்டை புகார்",
                            SubServiceId = 16
                        },
                        new
                        {
                            Id = 33,
                            Description = "පොදු බැංකු විමසීම්.",
                            LanguageId = 2,
                            Name = "පොදු විමසීම",
                            SubServiceId = 17
                        },
                        new
                        {
                            Id = 34,
                            Description = "பொது வங்கி விசாரணைகள்.",
                            LanguageId = 3,
                            Name = "பொது விசாரணை",
                            SubServiceId = 17
                        },
                        new
                        {
                            Id = 35,
                            Description = "පාරිභෝගික පැමිණිල්ලක් ලියාපදිංචි කරන්න.",
                            LanguageId = 2,
                            Name = "පැමිණිලි",
                            SubServiceId = 18
                        },
                        new
                        {
                            Id = 36,
                            Description = "வாடிக்கையாளர் புகாரைப் பதிவு செய்யுங்கள்.",
                            LanguageId = 3,
                            Name = "புகார்",
                            SubServiceId = 18
                        },
                        new
                        {
                            Id = 37,
                            Description = "ඩිජිටල් බැංකු සහාය.",
                            LanguageId = 2,
                            Name = "ඩිජිටල් බැංකුව",
                            SubServiceId = 19
                        },
                        new
                        {
                            Id = 38,
                            Description = "டிஜிட்டல் வங்கி உதவி.",
                            LanguageId = 3,
                            Name = "டிஜிட்டல் வங்கி",
                            SubServiceId = 19
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = "string",
                            Description = "Daily token sequence reset mode",
                            IsActive = true,
                            SettingKey = "TOKEN_RESET_MODE",
                            SettingValue = "DAILY"
                        },
                        new
                        {
                            Id = 2,
                            DataType = "bool",
                            Description = "Enable voice announcements on display",
                            IsActive = true,
                            SettingKey = "ENABLE_VOICE_ANNOUNCEMENT",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 3,
                            DataType = "bool",
                            Description = "Enable token printing on kiosk",
                            IsActive = true,
                            SettingKey = "ENABLE_PRINT_TOKEN",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 4,
                            DataType = "int",
                            Description = "Number of recently called tokens on display",
                            IsActive = true,
                            SettingKey = "DISPLAY_RECENT_CALL_COUNT",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = 5,
                            DataType = "int",
                            Description = "Number of waiting tokens on display",
                            IsActive = true,
                            SettingKey = "DISPLAY_WAITING_QUEUE_COUNT",
                            SettingValue = "5"
                        },
                        new
                        {
                            Id = 6,
                            DataType = "int",
                            Description = "Default estimated wait minutes",
                            IsActive = true,
                            SettingKey = "DEFAULT_ESTIMATED_WAIT_MINUTES",
                            SettingValue = "8"
                        },
                        new
                        {
                            Id = 7,
                            DataType = "int",
                            Description = "Kiosk auto return seconds after finish",
                            IsActive = true,
                            SettingKey = "KIOSK_AUTO_RETURN_SECONDS",
                            SettingValue = "5"
                        },
                        new
                        {
                            Id = 8,
                            DataType = "bool",
                            Description = "Priority tokens called before standard",
                            IsActive = true,
                            SettingKey = "ENABLE_PRIORITY_QUEUE",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 9,
                            DataType = "string",
                            Description = "Branch identifier",
                            IsActive = true,
                            SettingKey = "BRANCH_ID",
                            SettingValue = "BR-9904"
                        },
                        new
                        {
                            Id = 10,
                            DataType = "string",
                            Description = "Branch display name",
                            IsActive = true,
                            SettingKey = "BRANCH_NAME",
                            SettingValue = "Branch Alpha"
                        },
                        new
                        {
                            Id = 11,
                            DataType = "string",
                            Description = "Kiosk software version",
                            IsActive = true,
                            SettingKey = "KIOSK_VERSION",
                            SettingValue = "v2.4"
                        },
                        new
                        {
                            Id = 12,
                            DataType = "int",
                            Description = "Waiting threshold warning in minutes",
                            IsActive = true,
                            SettingKey = "WAIT_TIME_WARNING_MINUTES",
                            SettingValue = "10"
                        },
                        new
                        {
                            Id = 13,
                            DataType = "string",
                            Description = "Staff UI theme",
                            IsActive = true,
                            SettingKey = "STAFF_UI_THEME",
                            SettingValue = "ENTERPRISE_TEAL"
                        },
                        new
                        {
                            Id = 14,
                            DataType = "bool",
                            Description = "Regenerate token number on transfer",
                            IsActive = true,
                            SettingKey = "TRANSFER_REGENERATE_TOKEN",
                            SettingValue = "false"
                        },
                        new
                        {
                            Id = 15,
                            DataType = "int",
                            Description = "Staff console auto refresh interval",
                            IsActive = true,
                            SettingKey = "STAFF_AUTO_REFRESH_SECONDS",
                            SettingValue = "10"
                        },
                        new
                        {
                            Id = 16,
                            DataType = "bool",
                            Description = "Lock call next while active token exists",
                            IsActive = true,
                            SettingKey = "CALL_NEXT_LOCK_WHEN_ACTIVE_TOKEN",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 17,
                            DataType = "bool",
                            Description = "System online/offline flag",
                            IsActive = true,
                            SettingKey = "SYSTEM_ONLINE",
                            SettingValue = "true"
                        },
                        new
                        {
                            Id = 18,
                            DataType = "string",
                            Description = "Active token id label format",
                            IsActive = true,
                            SettingKey = "STAFF_TOKEN_ID_FORMAT",
                            SettingValue = "TK-{id}"
                        },
                        new
                        {
                            Id = 19,
                            DataType = "int",
                            Description = "Upcoming tokens shown on My Counter",
                            IsActive = true,
                            SettingKey = "STAFF_MY_COUNTER_UPCOMING_COUNT",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = 20,
                            DataType = "int",
                            Description = "Waiting count threshold for high queue pressure",
                            IsActive = true,
                            SettingKey = "STAFF_QUEUE_PRESSURE_HIGH_THRESHOLD",
                            SettingValue = "12"
                        },
                        new
                        {
                            Id = 21,
                            DataType = "int",
                            Description = "Allowed break minutes per shift",
                            IsActive = true,
                            SettingKey = "STAFF_BREAK_ALLOWANCE_MINUTES",
                            SettingValue = "60"
                        },
                        new
                        {
                            Id = 22,
                            DataType = "int",
                            Description = "Break minutes used in current shift",
                            IsActive = true,
                            SettingKey = "STAFF_BREAK_USED_MINUTES",
                            SettingValue = "15"
                        },
                        new
                        {
                            Id = 23,
                            DataType = "string",
                            Description = "Shift end time (HH:mm)",
                            IsActive = true,
                            SettingKey = "STAFF_SHIFT_END_TIME",
                            SettingValue = "17:00"
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CounterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedWaitMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastTransferredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SequenceDate")
                        .HasColumnType("date");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TokenNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TransferCount")
                        .HasColumnType("int");

                    b.Property<string>("TransferredFromTokenNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CalledAt")
                        .HasDatabaseName("IX_Tokens_CalledAt");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IX_Tokens_CompletedAt");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tokens_CreatedAt");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TokenNo")
                        .HasDatabaseName("IX_Tokens_TokenNo");

                    b.HasIndex("CounterId", "Status")
                        .HasDatabaseName("IX_Tokens_CounterId_Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Tokens_Status_CreatedAt");

                    b.HasIndex("Status", "QueuedAt")
                        .HasDatabaseName("IX_Tokens_Status_QueuedAt");

                    b.HasIndex("ServiceId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_Tokens_ServiceId_Status_CreatedAt");

                    b.HasIndex("SubServiceId", "SequenceDate", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Tokens_SubServiceId_SequenceDate_SequenceNo");

                    b.HasIndex("SubServiceId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_Tokens_SubServiceId_Status_CreatedAt");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.TokenStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CounterId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffUserId")
                        .HasColumnType("int");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("TokenId", "ChangedAt");

                    b.ToTable("TokenStatusHistories");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.VoiceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("VoiceTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventType = "TOKEN_CALLED",
                            IsActive = true,
                            LanguageId = 1,
                            TemplateText = "Token number {tokenNo}, please proceed to {counterName}"
                        },
                        new
                        {
                            Id = 2,
                            EventType = "TOKEN_CALLED",
                            IsActive = true,
                            LanguageId = 2,
                            TemplateText = "ටෝකන් අංකය {tokenNo}, කරුණාකර {counterName} වෙත එන්න"
                        },
                        new
                        {
                            Id = 3,
                            EventType = "TOKEN_CALLED",
                            IsActive = true,
                            LanguageId = 3,
                            TemplateText = "டோக்கன் எண் {tokenNo}, {counterName} க்குச் செல்லவும்"
                        });
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.CounterServiceAssignment", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Counter", "Counter")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("CounterAssignments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DailyTokenSequence", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.SubService", "SubService")
                        .WithMany("DailySequences")
                        .HasForeignKey("SubServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.DisplayMessage", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("DisplayMessages")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.ServiceTranslation", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("ServiceTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("Translations")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.StaffUser", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Counter", "Counter")
                        .WithMany("StaffUsers")
                        .HasForeignKey("CounterId");

                    b.Navigation("Counter");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubService", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("SubServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubServiceTranslation", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("SubServiceTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.SubService", "SubService")
                        .WithMany("Translations")
                        .HasForeignKey("SubServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Token", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Counter", "Counter")
                        .WithMany("Tokens")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("Tokens")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.Service", "Service")
                        .WithMany("Tokens")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartQ.Domain.Entities.SubService", "SubService")
                        .WithMany("Tokens")
                        .HasForeignKey("SubServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Language");

                    b.Navigation("Service");

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.TokenStatusHistory", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Token", "Token")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.VoiceTemplate", b =>
                {
                    b.HasOne("SmartQ.Domain.Entities.Language", "Language")
                        .WithMany("VoiceTemplates")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Counter", b =>
                {
                    b.Navigation("ServiceAssignments");

                    b.Navigation("StaffUsers");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Language", b =>
                {
                    b.Navigation("DisplayMessages");

                    b.Navigation("ServiceTranslations");

                    b.Navigation("SubServiceTranslations");

                    b.Navigation("Tokens");

                    b.Navigation("VoiceTemplates");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Service", b =>
                {
                    b.Navigation("CounterAssignments");

                    b.Navigation("SubServices");

                    b.Navigation("Tokens");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.SubService", b =>
                {
                    b.Navigation("DailySequences");

                    b.Navigation("Tokens");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SmartQ.Domain.Entities.Token", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
